### ISSUE TITLE
ability to toggle treasure maps and include them in the route plan

### ISSUE THREAD

**Issue by DaveB93** [jeanropke/RDR2CollectorsMap#173] opened 2019-10-08 20:20 UTC
**Is your feature request related to a problem? Please describe.**
I have a bunch of treasure maps,  it would be nice to be able to toggle them on, and then include them in the route map so I can easily include them in a run. 

**Describe the solution you'd like**
I'd like them to default off, with the ability to toggle them on by name

**Describe alternatives you've considered**
I've printed out my own map and labelled where they are, but I forget I've got them, and only really want to look at one thing. 

**Additional context**
Is this something you'd be interested in doing?  or accepting if a pull request was made?

**Comment by Rakmarok** [comment] 2019-10-08 23:58
That sounds pretty helpful.

I also got over 10 treasure maps from the Outlaw pass as well as looted ones. Including all possible locations by name would be nice.

**Comment by jeanropke** [comment] 2019-10-09 00:56
Duplicate of #130

**Closed by jeanropke** 2019-10-09 00:56 UTC
Labels: Suggestion
