### ISSUE TITLE
Treasure Maps

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#181] opened 2019-10-09 14:12 UTC
I would love to see the possibility to SHOW all treasure maps, then CHECK THEM ALL (so they are greyed out), then just UNCHECK the maps I have with me.
By doing so I would always be aware of an active treasure map in or nearby the area I am collecting stuff.

**Comment by iligalodin** [comment] 2019-10-09 15:12
so you wnd a submenu for the treasuremaps?

**Comment by DaveB93** [comment] 2019-10-09 18:21
Duplicate of #130

**Closed** 2019-10-09 20:42 UTC
