### ISSUE TITLE
Icons Fanning When Close Together

### ISSUE THREAD

**Issue by singemfrc** [jeanropke/RDR2CollectorsMap#543] opened 2019-12-17 22:18 UTC
On some of the new cycles there are 2 or 3 items that are so close together, you almost cant see that they are there on the map even zoomed in because they are right on top of each other, making it very hard to hide items from the map. Could you perhaps have them angle, so they fan out like a hand of cards?

**Comment by jeanropke** [comment] 2019-12-18 00:26
Duplicate of #538

**Closed by jeanropke** 2019-12-18 00:26 UTC
Labels: Suggestion
