### ISSUE TITLE
Jeanrpke map not displaying on microsoft edge since new cycles 

### ISSUE THREAD

**Issue by Markito87** [jeanropke/RDR2CollectorsMap#709] opened 2020-01-13 01:44 UTC
Since the update, not displaying any map or details, only legacy version with 3 cycles available? Any tips or advice for this xbox user?

**Comment by Senexis** [comment] 2020-01-13 18:54
Is this specifically about the Xbox One version of Edge? On PC it seems fine.

**Comment by Markito87** [comment] 2020-01-13 21:49
Yes, but only on my profile, which I should have mentioned sorry. On the same xbox1 console using another profile, it works as it should , unlike the 1 in question which only displays legacy version.

**Comment by AdamNortonUK** [comment] 2020-01-13 21:49
Have you tried refreshing the map in the browser? I only say this as on PC using Edge Chromium sometimes the map does not load on first load and a refresh usually sorts it.

**Comment by Markito87** [comment] 2020-01-13 21:53
Tried multiple times to be sure, no change? Its strange as on other profile its ok?

**Comment by Markito87** [comment] 2020-01-13 21:56
Its not a complete loss as i can get whats on offer depending whats available on Friday 1st 3 cycles. Just wanted to suss ouut why. Cheers tho y'all.

**Comment by AdamNortonUK** [comment] 2020-01-13 22:18
Tried clearing the cache / history for the browser on your profile. I don't have an Xbox so cannot help further than that but that might be the issue.

**Comment by jeanropke** [comment] 2020-01-15 10:43
Can you send a screenshot of the map?

**Comment by VanDuderBoss** [comment] 2020-01-16 16:24
Duplicate of #709

 I am having the same issue except on chrome. 

> Can you send a screenshot of the map?

Screenshot attached. 
![GitHub](https://user-images.githubusercontent.com/59970606/72542743-842c2b80-3839-11ea-8ca8-a562968c2041.JPG)

**Comment by CIAAGENTXXXXX** [comment] 2020-01-17 04:32
The map system seems to have the bug on mobile in all serch systems could you please let us know what cycle each is on today I already know the taro cards cups are on cycle 4

**Comment by jeanropke** [comment] 2020-01-17 14:15
@VanDuderBoss I'm using an CDN to map tiles. Can you open the developer console (F12) and send another screenshot?

That's how it should look like
![download (14)](https://user-images.githubusercontent.com/6243818/72618712-79959300-391a-11ea-98ef-29c89c56d1fb.png)

**Comment by VanDuderBoss** [comment] 2020-01-17 15:18
@jeanropke Good morning. Well I don't know if it was a combination of clearing my browsers cache out or what but the map seems to be working fine this morning. 

Screenshots attached. 
![RDO Map Works 1-17-2020 0715 PST](https://user-images.githubusercontent.com/59970606/72623052-4393e700-38f9-11ea-990c-7757d482fb54.JPG)
![RDO Console](https://user-images.githubusercontent.com/59970606/72623053-4393e700-38f9-11ea-9cff-fbaf831ccc76.JPG)
![RDO Console 2](https://user-images.githubusercontent.com/59970606/72623054-4393e700-38f9-11ea-969d-d913583ec01b.JPG)


If it's of any consequence I've checked to see if the map loads properly on Edge and Safari and I can confirm it loads and works properly.

**Comment by Senexis** [comment] 2020-01-28 15:43
The original issue, in which the Edge browser on Xbox doesn't work, seems to be resolved.

![image](https://user-images.githubusercontent.com/6360733/73279350-45a95000-41ed-11ea-8d07-b35913a70451.png)

**Closed by Senexis** 2020-01-28 15:43 UTC
Labels: Bug, Question
