### ISSUE TITLE
Sub selection individual items

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#99] opened 2019-10-02 22:44 UTC
I am currently completing all collections I've started. 
To do that I've compiled a list of all individual items based on your source code (items.json).
I keep track of found items using a Google Keep checkbox list on my smartphone.
That info I use to make a list of items I'm still missing.
From that list I make a string I can paste into the search box.
Because I use your item names that works very well.
But is somewhat cumbersome of course.
I use a combination of Google Keep, MS Excel and EditPlus to get it done :-)

For that purpose an option to sub select every item of every collection would be most practical.

**Comment by Mr-Schickadance** [comment] 2019-10-03 14:03
Yes it would be great if we could put a table containing all items into the code. I have done this on my computer but I don't know how to transfer this to GitHub (I'm new to GitHub). I have a drop down table that allows you to select specific items and have them appear on the map. I wrote a function for this and used css grids to lay it out as neatly as I could. Here's what it looks like (a scroll bar allows me to see all of the items, not just the first few you see in the picture):
![RDR2Map](https://user-images.githubusercontent.com/55929247/66133630-fb102200-e5c4-11e9-90cd-67075ef7305c.png)

**Comment by jeanropke** [comment] 2019-10-04 16:26
Duplicate of #39

**Closed by jeanropke** 2019-10-04 16:26 UTC
Labels: Suggestion
