### ISSUE TITLE
Collector Encounters (Tree Maps, Treasure Hunters, Grave Robbers)

### ISSUE THREAD

**Issue by IronJeff80** [jeanropke/RDR2CollectorsMap#271] opened 2019-10-26 17:02 UTC
These are random encounters specific to collector role:

**Treasure Hunter Locations: always found on cliff edges near treasure map search areas**
Treasure Hunter, The Heartlands: 
lat: -66.37510692265303
lng: 114.578125
https://youtu.be/9bhPMTCq_uk
https://rdr2map.com?notes=LfNN6nCEWB1 

Treasure Hunter, Cumberland Falls:
lat: -57.20290953465374
lng: 93.96875
https://youtu.be/B6-dUHzeq50
https://rdr2map.com?notes=CDqKHGixgk3 

Treasure Hunter, Riggs Station:
lat: -69.921875 
lng: 94.5078125
https://youtu.be/jiOp8qSHxwI 
https://youtu.be/g3AgRW8URZg 
https://rdr2map.com?notes=BAnj6zGfgsc 

Treasure Hunter, Dakota River:
lat: -61.28125 
lng: 91.2734375
https://youtu.be/oth6i6O7zzY 
https://rdr2map.com?notes=2bXWWXkh5af 

Treasure Hunter, Monto’s Nest:
lat: -65.2734375 
lng: 85.734375
https://youtu.be/vXerJ2j6YoU 
https://rdr2map.com?notes=DJStaXYDoMn 

Treasure Hunter, Citadel Rock:
lat: -57.65625 
lng: 111.890625
https://youtu.be/08URpyjzvPs 
https://rdr2map.com?notes=ChVldwjRozd 

Treasure Hunter, Heartland Oil Fields:
lat: -54.8515625 
lng: 123.953125
https://youtu.be/vn2tOS6Dp0U 
https://rdr2map.com?notes=1egm8RDjQUI 

Treasure Hunter, Wallace Station
lat: -59.046875 
lng: 89.859375
https://youtu.be/29aiBR_qRD8 
https://rdr2map.com?notes=JfdZDNqQZTO 

**Treasure Map Locations, found mostly at night, stuck to trees. Look for lantern light**

Treasure Map, Del Lobo Rock:
lat: -119.53498268036311 
lng: 53.625
https://rdr2map.com?notes=9jc5lutWRG9

Treasure Map, Cumberland Forrest: 
lat: -47.6171875 
lng: 112.2109375
https://rdr2map.com?notes=JYIoosCxAag 

Treasure Map, The Heartlands
lat: -63.1015625 
lng: 122.359375
https://rdr2map.com?notes=4P7KoNlNJCi 

Treasure Map, Hanging Rock
lat: -98.6328125 
lng: 57.71875
https://youtu.be/WKjQrKzGSUk 
https://rdr2map.com?notes=EDL4RHXDgxt 

Treasure Map: Dewberry Creek
lat: -63.1796875 
lng: 128.1640625
https://youtu.be/KoNVcQzlrdI 
https://rdr2map.com?notes=GD6cgdkL4bm 

Treasure Map: Heartland Overflow
lat: -57.1796875 
lng: 126.84375
https://youtu.be/7yOlX7hWJ3c 
https://rdr2map.com?notes=6BiL4UTvgAs 

Treasure Map: Kamassa River
lat: -60.5625 
lng: 144.1640625
https://youtu.be/dv4egr1SYjY 
https://rdr2map.com?notes=DtmEt1NrrPT 

Treasure Map: Flatneck Station
lat: -68.90025158265648 
lng: 104.2421875
https://youtu.be/4xTHdvvsoYQ 
https://rdr2map.com?notes=1EvEm3nJBrl 

Treasure Map, Van Horn
lat: -60.796875
lng: 152.859375
https://rdr2map.com?notes=Ns4wR9dqEK

Treasure Map, Fort Wallace
lat: -41.7109375
lng: 116.9921875
https://rdr2map.com?notes=7ktSuaV1NVw

Treasure Map, Blackwater
lat: -80.96875
lng: 92.0859375
https://rdr2map.com?notes=6KWBERhxuDD

Treasure Map, Little Creek
lat: -54.953125
lng: 84.578125
https://rdr2map.com?notes=TWmufenlKZ

Treasure Map, Moonstone Pond
lat: -45.51450001131039 
lng: 131.20049762389257
https://rdr2map.com?notes=BW5dFTnbj9c

Treasure Map, Thieves Landing
lat: -101.22408026755852
lng: 88.9375
https://rdr2map.com?notes=4O84IEnnpzj 

Treasure Map, Stillwater Creek
lat: -102.6618618904755 
lng: 79.82931533706275
https://youtu.be/1b6aQs4ggdc 
https://rdr2map.com?notes=HljodAZjVaK  

Treasure Map, O’Creagh’s Run
lat: -39.99624119087434 
lng: 139
https://rdr2map.com?notes=FiqzP2UhC6w

Treasure Map, Great Plains
lat: -89.30661729574773
lng: 86.7890625
https://youtu.be/MaConhFXCU8 
https://rdr2map.com?notes=DTCAzFld3zm

Treasure Map, Upper Montana River
lat: -75.5827385929288 
lng: 91.6640625
https://rdr2map.com?notes=2lL0WuT4ixC

Treasure Map, Dakota River South
lat: -64.73331118609651 
lng: 104.0234375
https://rdr2map.com?notes=LtAcMGZLIoj

Treasure Map, Dakota River North
lat: -61.450493460344006 
lng: 96.3359375
https://rdr2map.com?notes=50xOT7DFCYV 

Treasure Map, Monto’s Nest
lat: -67.2829409042045 
lng: 89.359375
https://youtu.be/XBN3ptaLQx4 
https://rdr2map.com?notes=Civp0RUmQg5 

**Grave Digger Treasure Map Hunts**

Grave Digger, Saint Denis
lat: -80.265625 
lng: 154.0546875
https://rdr2map.com?notes=LfLk1Xjjlho 

Grave Digger, Strawberry
lat: -67.21875 
lng: 83.9765625
https://rdr2map.com?notes=Ch0flFOLGOy 

Grave Digger, Valentine
lat: -50.8984375 
lng: 107.8046875
https://rdr2map.com?notes=IXfe6toxZpP 

Grave Digger, Rhodes
lat: -82.578125 
lng: 131.1328125
https://youtu.be/sin6Q97gA5k 
https://rdr2map.com?notes=2icad9kyGjN 

**Random Bird Eggs: White Dot on mini map indicates predator going to eat the eggs**
Bird Egg Encounter: Moonstone Pond
lat: -45.3125 
lng: 130.59375
https://rdr2map.com?notes=1GQnuFEi8zV 

Bird Egg Encounter: Elysian Pool
lat: -49 
lng: 149.6015625
https://rdr2map.com?notes=2GsTZAbJB82 

Bird Egg Encounter, Heartland Overflow
lat: -54.625 
lng: 128.78125
https://rdr2map.com?notes=KjPovbYMejC 

Bird Egg Encounter, Lake Owanjila
lat: -69.3046875 
lng: 74.2734375
https://rdr2map.com?notes=AC3Md1vhOaj 

Bird Egg Encounter, Kamassa River North
lat: -38.653696846631625 
lng: 146.7265625
https://rdr2map.com?notes=DY3GXfVWtOv 

Bird Egg Encounter, Bluewater Marsh
lat: -71.21198638318204 
lng: 148.640625
https://rdr2map.com?notes=73vUoqxn4Ys 

Bird Egg Encounter, Burned Town
lat: -64.53191441710463 
lng: 104.8828125
https://rdr2map.com?notes=rWPU4YQkj1
https://youtu.be/uNYFI1Az-d4 

**Wounded Animals: Red or White Paw icon on mini map reveals an wounded animal from which you can find an Arrowhead**

Wounded Animal, Cumberland Forest
lat: -45.15625 
lng: 116.0234375
https://rdr2map.com?notes=GdEiC3yWrI1 

Wounded Animal, Valentine
lat: -55.8046875 
lng: 103.15625
https://rdr2map.com?notes=AVmj57L0GQP 

Wounded Predator, Strawberry
lat: -67.28125 
lng: 83.703125
https://rdr2map.com?notes=KS8rTVIkjTO 

Wounded Predator, Wapiti
lat: -32.2265625 
lng: 117.8359375
https://rdr2map.com?notes=4HsKEGaYr10 

**Barking Dog, Follow the dog to potentially reveal a collectable or an ambush**

Barking Dog, Annesburg
lat: -41.3828125 
lng: 154.734375
https://rdr2map.com?notes=6VhEfnseCga 

Barking Dog, Quaker’s Cove
lat: -93.296875 
lng: 88.6015625
https://rdr2map.com?notes=1WKznVIBElr 

Barking Dog, Manmade Mutant House
lat: -56.21875 
lng: 154.3125
https://rdr2map.com?notes=KTH3jxoDA49 

**Fame Seeker**

Fame Seeker, Lower Montana River
lat: -97.109375 
lng: 80.0703125
https://rdr2map.com?notes=DmLhH1F28xt

**Comment by IronJeff80** [comment] 2019-10-26 17:05
Can probably be merged with Issue 225 and 207

**Comment by jeanropke** [comment] 2019-10-26 19:52
I'll change how the markers are rendered. Look at https://jeanropke.github.io/RDOMap/.

**Comment by jeanropke** [comment] 2019-10-26 20:46
Duplicate of #225 & #207

**Comment by IronJeff80** [comment] 2019-11-04 07:49
Treasure Hunter, Heartland Oil Fields:
lat: -54.8515625 
lng: 123.953125
https://youtu.be/8CSmhfofwN8

**Comment by IronJeff80** [comment] 2019-11-08 07:10
Treasure Hunter, Wallace Station
lat: -59.046875 
lng: 89.859375
https://youtu.be/29aiBR_qRD8 

Treasure Map: Heartland Overflow
lat: -57.1796875 
lng: 126.84375
https://youtu.be/7yOlX7hWJ3c 

Treasure Map: Kamassa River
lat: -60.5625 
lng: 144.1640625
https://youtu.be/dv4egr1SYjY 

Grave Digger, Rhodes
lat: -82.578125 
lng: 131.1328125
https://youtu.be/sin6Q97gA5k

**Comment by ArthurMorganRDR** [comment] 2019-11-16 23:24
Found 2 locations, but didn't check the above list, so sorry if I duplicate:

lat: -57.05078125
lng: 126.765625

lat: -68.890625
lng: 104.6640625

**Comment by IronJeff80** [comment] 2019-11-20 09:57
@jeanropke 
If I post something like this for each Item, would it be beneficial?
{"text": "treemap_01", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-119.53498268036311", "y": "53.625"}

{"key":"tree_map_01.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_01_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees, mainly at night. Look for lantern light."},{"key":"tree_map_01_2.desc","value":" Tree Maps are Random Encounters. They spawn on trees, mainly at night. Look for lantern light."},{"key":"tree_map_01_3.desc","value":" Tree Maps are Random Encounters. They spawn on trees, mainly at night. Look for lantern light."}

**Comment by IronJeff80** [comment] 2019-11-20 10:42
{"text": "treemap_01", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-119.53498268036311", "y": "53.625"},
{"text": "treemap_02", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-47.6171875", "y": "112.2109375"},
{"text": "treemap_03", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-63.1015625", "y": "122.359375"},
{"text": "treemap_04", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-98.6328125", "y": "57.71875"},
{"text": "treemap_05", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-57.1796875", "y": "126.84375"},
{"text": "treemap_06", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-63.1796875", "y": "128.1640625"},
{"text": "treemap_07", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-60.5625", "y": "144.1640625"},
{"text": "treemap_08", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-68.90025158265648", "y": "104.2421875"},
{"text": "treemap_09", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-60.796875", "y": "152.859375"},
{"text": "treemap_10", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-41.7109375", "y": "116.9921875"},
{"text": "treemap_11", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-80.96875", "y": "92.0859375"},
{"text": "treemap_12", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-54.953125", "y": "84.578125"},
{"text": "treemap_13", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "45.51450001131039", "y": "131.20049762389257"},
{"text": "treemap_14", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-101.22408026755852", "y": "88.9375"},
{"text": "treemap_15", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-102.6618618904755", "y": "79.82931533706275"},
{"text": "treemap_16", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-39.99624119087434", "y": "139"},
{"text": "treemap_17", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-89.30661729574773", "y": "86.7890625"},
{"text": "treemap_18", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-75.5827385929288", "y": "91.6640625"},
{"text": "treemap_19", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-64.73331118609651", "y": "104.0234375"},
{"text": "treemap_20", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-61.450493460344006", "y": "96.3359375"},
{"text": "treemap_21", "day": {1, 2, 3}, "tool": "0", "icon": "treemap", "x": "-67.2829409042045", "y": "89.359375"},

**Comment by IronJeff80** [comment] 2019-11-20 10:43
{"key":"tree_map_01.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_01_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_01_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_01_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_02.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_02_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_02_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_02_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_03.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_03_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_03_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_03_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_04.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_04_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_04_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_04_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_05.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_05_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_05_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_05_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_06.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_06_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_06_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_06_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_07.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_07_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_07_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_07_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_08.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_08_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_08_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_08_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_09.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_09_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_09_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_09_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_10.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_10_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_10_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_10_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_11.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_11_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_11_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_11_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_12.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_12_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_12_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_12_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_13.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_13_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_13_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_13_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_14.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_14_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_14_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_14_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_15.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_15_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_15_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_15_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_16.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_16_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_16_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_16_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_17.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_17_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_17_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_17_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_18.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_18_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_18_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_18_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_19.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_19_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_19_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_19_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_20.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_20_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_20_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_20_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},
{"key":"tree_map_21.name","value":"Treasure Map stuck on Tree"},{"key":"tree_map_21_1.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_21_2.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},{"key":"tree_map_21_3.desc","value":"Tree Maps are Random Encounters. They spawn on trees mainly at night. Look for lantern light."},

**Comment by IronJeff80** [comment] 2019-11-20 11:00
{"text": "treasure_hunter_01", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-66.37510692265303", "y": "114.578125"},
{"text": "treasure_hunter_02", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-57.20290953465374", "y": "93.96875"},
{"text": "treasure_hunter_03", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-69.921875", "y": "94.5078125"},
{"text": "treasure_hunter_04", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-61.28125", "y": "91.2734375"},
{"text": "treasure_hunter_05", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-65.2734375", "y": "85.734375"},
{"text": "treasure_hunter_06", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-57.65625", "y": "111.890625"},
{"text": "treasure_hunter_07", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-54.8515625", "y": "123.953125"},
{"text": "treasure_hunter_08", "day": {1, 2, 3}, "tool": "0", "icon": "treasure_hunter", "x": "-59.046875", "y": "89.859375"},

**Comment by IronJeff80** [comment] 2019-11-20 11:02
{"key":"treasure_hunter_01.name","value":"Treasure Hunter"},{"key":"treasure_hunter_01_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_01_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_01_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_02.name","value":"Treasure Hunter"},{"key":"treasure_hunter_02_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_02_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_02_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_03.name","value":"Treasure Hunter"},{"key":"treasure_hunter_03_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_03_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_03_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_04.name","value":"Treasure Hunter"},{"key":"treasure_hunter_04_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_04_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_04_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_05.name","value":"Treasure Hunter"},{"key":"treasure_hunter_05_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_05_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_05_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_06.name","value":"Treasure Hunter"},{"key":"treasure_hunter_06_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_06_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_06_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_07.name","value":"Treasure Hunter"},{"key":"treasure_hunter_07_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_07_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_07_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},
{"key":"treasure_hunter_08.name","value":"Treasure Hunter"},{"key":"treasure_hunter_08_1.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_08_2.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},{"key":"treasure_hunter_08_3.desc","value":"Treasure Hunters are Random Encounters. Keep an eye out for a white blip on the mini map to locate them."},

**Comment by IronJeff80** [comment] 2019-11-21 22:18
@jeanropke 
Treasure Hunter, Wallace Station #2
https://youtu.be/3nwsxNKDOu8 
https://rdr2map.com?notes=2XaQHLCc1F1 
{"text": "treasure_hunter_09", "x": "-59.0705", "y": "91.4296"}

**Comment by IronJeff80** [comment] 2019-11-22 07:16
{"key": "egg_encounter.name","value":"Bird Egg Nest Encounter"},
	{"key": "egg_encounter.desc","value":"These are Random Encounters.  A white blip on the mini map will indicate the encounter. You must get to the egg nest before the predator eats the eggs."},

{"key": "grave_robber.name","value":"Grave Robber Encounter"},
	{"key": "grave_robber.desc","value":"This is a Random Encounter. A white blip on the mini map will indicate the encounter. Approach the grave robber to accept the mission. You have limited time to search up to 7 locations for a collectable item before the lawmen come."}


"egg_encounter": [
	{"text": "egg_encounter_01", "x": "-54.625", "y": "128.7812"},
	{"text": "egg_encounter_02", "x": "-69.3046", "y": "74.2734"},
	{"text": "egg_encounter_03", "x": "-38.6536", "y": "146.7265"},
	{"text": "egg_encounter_04", "x": "-71.2119", "y": "148.6406"},
	{"text": "egg_encounter_05", "x": "-64.5319", "y": "104.8828"},
	{"text": "egg_encounter_06", "x": "-45.3125", "y": "130.5937"},
	{"text": "egg_encounter_07", "x": "-49", "y": "149.6015"}
],
"grave_robber": [
	{"text": "grave_robber_01", "x": "-80.2656", "y": "154.0546"},
	{"text": "grave_robber_02", "x": "-67.2187", "y": "83.9765"},
	{"text": "grave_robber_03", "x": "-50.8984", "y": "107.8046"},
	{"text": "grave_robber_04", "x": "-82.5781", "y": "131.1328"}
]

**Comment by IronJeff80** [comment] 2019-11-22 21:36
{"text": "treasure_hunter_09", "x": "-59.0705", "y": "91.4296"},
{"text": "treasure_hunter_10", "x": "-60.6961", "y": "101.6484"},
{"text": "treasure_hunter_11", "x": "-64.4060", "y": "123.0156"}


Update to tree_map_19 (more precise)
{"text": "tree_map_19", "x": "-64.6267", "y": "103.7656"}

**Comment by IronJeff80** [comment] 2019-11-24 01:41
{"text": "tree_map_20", "x": "-99.7897", "y": "87.3984"}

**Comment by IronJeff80** [comment] 2019-11-24 18:48
{"text": "egg_encounter_08", "x": "-100.5174", "y": "84.3671"}

**Closed** 2019-12-04 22:46 UTC
